OKBatchTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('kombuchacalendar/', include('kombuchacalendar.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('kombuchacalendar/', include('kombuchacalendar.urls')),
    path('', RedirectView.as_view(url='kombuchacalendar/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import SignUpView

app_name = 'accounts'
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
]

kombuchacalendar/urls.py
from django.urls import path
from . import views

app_name = 'kombuchacalendar'
urlpatterns = [
    path('', views.index, name='index'),
    path('brew_batch/', views.brew_batch, name='brew_batch'),
    path('batches/', views.BatchListView.as_view(), name='batches'),
    path('batch/<int:pk>/', views.BatchDetailView.as_view(), name='batch_detail'),
    path('batch_update/<int:batch_id>/', views.batch_update, name='batch_update'),
    path('batch/<int:batch_id>/archive/', views.batch_archive, name='batch_archive'),
    path('archive/', views.ArchiveListView.as_view(), name='archive'),
    path('batch/<int:batch_id>unarchive', views.batch_unarchive, name='batch_unarchive'),
]

kombuchacalendar/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone

# Create your models here.


class Batch(models.Model):
    brewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, help_text="Give your batch a name if you want...")
    description = models.TextField(help_text="Batch Size, SCOBY Origin, etc. ")
    date_brewed = models.DateField(default=timezone.now)

    STARTER_TYPE = (
        ('k', 'Kombucha'),
        ('j', 'Jun')
    )

    starter_type = models.CharField(max_length=1, default='k', choices=STARTER_TYPE)

    TEA_FLAVORS = (
        ('bl', "Black Tea"),
        ('pg', "Pear Ginger Black Tea"),
        ('bb', "Blueberry Black Tea"),
        ('jg', "Jasmine Green Tea"),
        ('sg', "Strawberry Green Tea"),
        ('cg', "Coconut Green Tea"),
    )

    tea_flavor = models.CharField(max_length=2, default='bl', choices=TEA_FLAVORS)

    SWEETENER_USED = (
        ('h', 'Honey'),
        ('s', 'Sugar'),
    )

    sweetener = models.CharField(max_length=1, default='s', choices=SWEETENER_USED)

    archive = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'batches'

    def starter_type_verbose(self):
        return dict(Batch.STARTER_TYPE)[self.starter_type]

    @property
    def date_brewed_display(self):
        return self.date_brewed.strftime(settings.UPDATED_DATE_FORMAT)

    def __str__(self):
        return f'{self.name}({self.get_starter_type_display()}):{self.date_brewed_display}'

    def get_absolute_url(self):
        return reverse('kombuchacalendar:batch_detail', kwargs={'pk': self.pk})

kombuchacalendar/forms.py
import datetime
from django import forms
from django.utils import timezone
from .models import Batch


class BrewBatchForm(forms.ModelForm):
    class Meta:
        model = Batch
        fields = ['starter_type', 'tea_flavor', 'sweetener', 'date_brewed', 'description', 'name',]

kombuchacalendar/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views import generic
from .models import Batch
from .forms import BrewBatchForm
from django.urls import reverse_lazy, reverse


# Create your views here.
def index(request):
    num_batches = Batch.objects.filter(archive=False).count

    context = {
        'num_batches': num_batches,
    }
    return render(request, 'index.html', context)


@login_required
def brew_batch(request):
    # form to create a new kombucha batch
    if request.method != 'POST':
        # no data submitted, creates blank form
        form = BrewBatchForm()
    else:
        # POST data submitted; process data
        form = BrewBatchForm(data=request.POST)
        if form.is_valid():
            brew = form.save(commit=False)
            brew.brewer = request.user
            brew.save()
            return redirect('kombuchacalendar:batches')
    context = {'form': form}
    return render(request, 'kombuchacalendar/brew_batch.html', context)


class BatchListView(LoginRequiredMixin, generic.ListView):
    model = Batch
    template_name = 'kombuchacalendar/batch_list.html'

    def get_queryset(self):
        return Batch.objects.filter(brewer=self.request.user, archive=False)


class BatchDetailView(LoginRequiredMixin, generic.DetailView):
    model = Batch
    template_name = 'kombuchacalendar/batch_detail.html'


@login_required
def batch_update(request, batch_id):
    batch = Batch.objects.get(id=batch_id)

    if request.method != 'POST':
        # prefill form with current entry
        form = BrewBatchForm(instance=batch)
    else:
        # POST data submitted, process data
        form = BrewBatchForm(instance=batch, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('kombuchacalendar:batch_detail', pk=batch.id)

    context = {'form': form, 'batch': batch}
    return render(request, 'kombuchacalendar/batch_update.html', context)


@login_required
def batch_archive(request, batch_id):
    batch = Batch.objects.get(id=batch_id)

    if batch.archive is False:
        batch.archive = True
        batch.save()
        return redirect('kombuchacalendar:archive')


class ArchiveListView(LoginRequiredMixin, generic.ListView):
    model = Batch
    template_name = 'kombuchacalendar/archive_list.html'

    def get_queryset(self):
        return Batch.objects.filter(brewer=self.request.user, archive=True)


@login_required
def batch_unarchive(request, batch_id):
    batch = Batch.objects.get(id=batch_id)

    if batch.archive is True:
        batch.archive = False
        batch.save()
        return redirect('kombuchacalendar:batches')

templates/kombuchacalendar/archive_list.html
{% extends 'base.html' %}

{% block content %}

  <h1>Past Booches, {{ user.first_name }}?</h1>
  {% if batch_list %}
    <ul>
        {% for batch in batch_list %}
          <li>
            <a href="{{ batch.get_absolute_url }}">{{ batch }}</a>
          </li>
        {% endfor %}
    </ul>
  {% else %}
    <p>
        You don't have any archived batches
    </p>
  {% endif %}
    <p>
        <a href="{% url 'kombuchacalendar:batches' %}">Back to Booches?</a>
    </p>
{% endblock content %}

templates/kombuchacalendar/batch_detail.html
{%  extends 'base.html' %}

{% block content %}
  <h1>{{ batch.name }}</h1>
  <h2>{{ batch.date_brewed }}</h2>
    <p>{{ batch.get_starter_type_display }} brewed with {{ batch.get_tea_flavor_display }} and
        {{ batch.get_sweetener_display }}</p>
    <p>{{ batch.description }}</p>

    <p>
        <a href="{% url 'kombuchacalendar:batch_update' batch.id %}">Update Batch Details</a>
    </p>
    {% if batch.archive == False %}
    <p>
        <a href="{% url 'kombuchacalendar:batch_archive' batch.id %}"><button>Archive Batch</button></a>
    </p>
    {% else %}
    <p>
        <a href="{% url 'kombuchacalendar:batch_unarchive' batch.id %}"><button>Unarchive Batch</button></a>
    </p>
    {% endif %}
    <p>
        <a href="{% url 'kombuchacalendar:batches' %}"> Back to Brewery</a>
    </p>
{% endblock content %}

templates/kombuchacalendar/batch_list.html
{% extends 'base.html' %}

{% block content %}

  <h1>What's Boochin', {{ user.first_name }}?</h1>
  {% if batch_list %}
    <ul>
        {% for batch in batch_list %}
          <li>
            <a href="{{ batch.get_absolute_url }}">{{ batch }}</a>
          </li>
        {% endfor %}
    </ul>
  {% else %}
    <p>You aren't brewing anything right now!</p>
  {% endif %}
    <p>
        <a href="{% url 'kombuchacalendar:brew_batch' %}">Start Brewing?</a>
    </p>
    <p>
        <a href="{% url 'kombuchacalendar:archive' %}">Past Batches</a>
    </p>
    <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Log Out</button>
    </form>
{% endblock content %}

templates/kombuchacalendar/batch_update.html
{%  extends 'base.html' %}

{% block content %}

    <p><a href="{% url 'kombuchacalendar:batch_detail' batch.id %}">{{ batch }}</a></p>

    <p>Batch Update:</p>

    <form action="{% url 'kombuchacalendar:batch_update' batch.id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
    <button name="submit">Update Batch</button>
    </form>

{% endblock content %}

templates/kombuchacalendar/brew_batch.html
{% extends 'base.html' %}

{% block content %}

<h1>Lets Brew!</h1>

<form action="{% url 'kombuchacalendar:brew_batch' %}" method="post">
  {% csrf_token %}
  {{ form.as_div }}
  <button name="submit">Brew It!</button>
</form>

{% endblock %}