OKBatchTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('kombuchacalendar/', include('kombuchacalendar.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('kombuchacalendar/', include('kombuchacalendar.urls')),
    path('', RedirectView.as_view(url='kombuchacalendar/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import SignUpView

app_name = 'accounts'
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
]

kombuchacalendar/urls.py
from django.urls import path
from . import views

app_name = 'kombuchacalendar'
urlpatterns = [
    path('', views.index, name='index'),
    path('brew_batch/', views.brew_batch, name='brew_batch'),
    path('batches/', views.BatchListView.as_view(), name='batches'),
    path('batch/<int:pk>/', views.BatchDetailView.as_view(), name='batch_detail'),
    path('batch_update/<int:batch_id>/', views.batch_update, name='batch_update'),
    path('batch/<int:batch_id>/archive/', views.batch_archive, name='batch_archive'),
    path('archive/', views.ArchiveListView.as_view(), name='archive'),
    path('batch/<int:batch_id>unarchive', views.batch_unarchive, name='batch_unarchive'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Kombucha Batch Tracker{% endblock %}</title>
</head>

<body {% block style %} style="background-color:darkcyan;" {% endblock %}>
  <main>
    {% block header %}
        <img src="{% static 'kombuchacalendar/OKlogo.png' %}" alt="Logo">
    {% endblock header %}
    {% block content %}
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{  message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endif %}
    {% endblock %}
  </main>
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title %}OKBT Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!
<p><a href="{% url 'password_change' %}">Password Change</a></p>
<form action="{% url 'logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>
{% else %}
<p>You are not logged in</p>
<p><a href="{% url 'password_reset' %}">Password Reset</a></p>
<p><a href="{% url 'login' %}">Log In</a></p>
<p><a href="{% url 'signup' %}">Sign Up</a></p>
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}OKBT Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <h1>Welcome to {{ user.first_name }}'s Kombucha Factory!</h1>
    <h2>You have {{ user.num_batches }} batches of Kombucha brewing.</h2>
    <h3> <a href="{% url 'kombuchacalendar:batches' %}">Take a Look!</a></h3>
    <h4><a href="{% url 'kombuchacalendar:brew_batch' %}">Start Brewing?</a></h4>
<p><a href="{% url 'password_change' %}">Password Change</a></p>
<form action="{% url 'logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>
{% else %}
<p>You are not logged in</p>
<p><a href="{% url 'login' %}">Log In</a></p>
<p><a href="{% url 'password_reset' %}">Forgot Password?</a></p>
<p><a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endif %}
{% endblock %}